# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment mappings
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

# Та же версия NeoForge, что стоит в TNP Limitless 8
neo_version=21.1.244
loader_version_range=[1,)

# Mod
mod_id=randomizer
mod_name=Universal Randomizer
mod_license=All Rights Reserved
mod_version=0.2.0
mod_group_id=dev.vect.randomizer